# Generated by Django 2.2.6 on 2019-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tg_user',
            name='tg_chat_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tg_user',
            name='age',
            field=models.CharField(max_length=5),
        ),
    ]
